# Generated by Django 4.2.2 on 2023-06-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workouts_gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название тренировки')),
                ('description', models.CharField(max_length=250, verbose_name='Описание тренировки')),
                ('full_text', models.TextField(verbose_name='Упражнения и дозировка нагрузки')),
            ],
        ),
        migrations.CreateModel(
            name='Workouts_swimming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название тренировки')),
                ('description', models.CharField(max_length=250, verbose_name='Описание тренировки')),
                ('full_text', models.TextField(verbose_name='Упражнения и дозировка нагрузки')),
            ],
        ),
        migrations.CreateModel(
            name='Workouts_swimming_pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название тренировки')),
                ('description', models.CharField(max_length=250, verbose_name='Описание тренировки')),
                ('full_text', models.TextField(verbose_name='Упражнения и дозировка нагрузки')),
            ],
        ),
    ]
