# Generated by Django 4.2.2 on 2023-06-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Ваше имя')),
                ('age', models.IntegerField(verbose_name='Ваш возраст')),
                ('purpose', models.CharField(max_length=250, verbose_name='Желаемый результат от занятий')),
                ('comment', models.CharField(max_length=250, verbose_name='Комментарий')),
            ],
        ),
    ]
