# Generated by Django 4.2.2 on 2023-06-29 21:39

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_alter_registrations_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
